SELECT ENG.Numéro, ENG.Date, ENG.Montant AS "ENGAGEMENTS", PAY.Montant AS "PAYMENT CUMULÉ", ENG.Montant - PAY.Montant AS "DIFFERENCE"
FROM
(
	SELECT ENG1.Numéro, ENG1.Date, ENG2.Montant
	FROM
	(
		SELECT MOUVEMENTS.Numéro, MAX(MOUVEMENTS.Date) AS Date
		FROM MOUVEMENTS
		WHERE MOUVEMENTS.Type = "ENG"
		GROUP BY MOUVEMENTS.Numéro
	) ENG1,
	(
		SELECT MOUVEMENTS.Numéro, MOUVEMENTS.Date, MOUVEMENTS.Montant
		FROM MOUVEMENTS
		WHERE MOUVEMENTS.Type = "ENG"
	) ENG2
	WHERE ENG1.Numéro = ENG2.Numéro AND ENG1.Date = ENG2.Date
) ENG
INNER JOIN
(
	SELECT MOUVEMENTS.Numéro, SUM(MOUVEMENTS.Montant) AS "Montant"
	FROM MOUVEMENTS
	WHERE MOUVEMENTS.Type = "PAY"
	GROUP BY MOUVEMENTS.Numéro
) PAY
ON ENG.Numéro = PAY.Numéro
WHERE ENG.Montant < PAY.Montant;
