SELECT OPERATIONS.Numéro, OPERATIONS.MO, CHAPITRES.BUREAU, OPERATIONS.Intitulé, OPERATIONS.Date_Insc, OPERATIONS.MICL
FROM OPERATIONS
INNER JOIN CHAPITRES
ON SUBSTRING(OPERATIONS.Numéro, 7, 3) = CHAPITRES.Numéro
WHERE OPERATIONS.MICL != "N L" AND OPERATIONS.Numéro NOT LIKE "%00" AND OPERATIONS.Numéro NOT IN
(
    SELECT MOUVEMENTS.Numéro
    FROM MOUVEMENTS
    WHERE MOUVEMENTS.Type = "ENG"
)
ORDER BY CHAPITRES.BUREAU, OPERATIONS.MO ASC; 
