SELECT OPERATIONS.Numéro, OPERATIONS.APA AS "APA", ENG.Montant AS "ENG", OPERATIONS.APA - ENG.Montant AS "DIFF"
FROM OPERATIONS
INNER JOIN
(
    SELECT MOUVEMENTS.Numéro, MAX(MOUVEMENTS.Date), MOUVEMENTS.Montant
    FROM MOUVEMENTS
    WHERE MOUVEMENTS.Type = "ENG"
    GROUP BY MOUVEMENTS.Numéro
) ENG
ON OPERATIONS.Numéro = ENG.Numéro
WHERE OPERATIONS.APA < ENG.Montant
