SELECT ENG.Numéro, ENG.Date, ENG.Montant AS "ENGAGEMENTS", PAY.Montant AS "PAYMENT CUMULÉ", ENG.Montant - PAY.Montant AS "DIFFERENCE"
FROM
(
	SELECT MOUVEMENTS.Numéro, MOUVEMENTS.Montant, MAX(MOUVEMENTS.Date) AS "Date"
	FROM MOUVEMENTS
	WHERE MOUVEMENTS.Type = "ENG"
	GROUP BY MOUVEMENTS.Numéro
) ENG
INNER JOIN
(
	SELECT MOUVEMENTS.Numéro, SUM(MOUVEMENTS.Montant) AS "Montant"
	FROM MOUVEMENTS
	WHERE MOUVEMENTS.Type = "PAY"
	GROUP BY MOUVEMENTS.Numéro ) PAY
ON ENG.Numéro = PAY.Numéro
WHERE ENG.Montant < PAY.Montant;
