SELECT OPERATIONS.Numéro, OPERATIONS.APA, ENG.Montant
FROM OPERATIONS
INNER JOIN
(
    SELECT ENG1.Numéro, ENG1.Date, ENG2.Montant
	FROM
	(
		SELECT MOUVEMENTS.Numéro, MAX(MOUVEMENTS.Date) AS Date
		FROM MOUVEMENTS
		WHERE MOUVEMENTS.Type = "ENG"
		GROUP BY MOUVEMENTS.Numéro
	) ENG1,
	(
		SELECT MOUVEMENTS.Numéro, MOUVEMENTS.Date, MOUVEMENTS.Montant
		FROM MOUVEMENTS
		WHERE MOUVEMENTS.Type = "ENG"
	) ENG2
	WHERE ENG1.Numéro = ENG2.Numéro AND ENG1.Date = ENG2.Date
) ENG
ON OPERATIONS.Numéro = ENG.Numéro
WHERE OPERATIONS.APA < ENG.Montant
