SELECT LEFT(CHAPITRES.SS, 1) AS "S", CHAPITRES.SS AS "SS", CHAPITRES.Numéro AS "CHP", CONCAT(OPERATIONS.Numéro, "\n", OPERATIONS.Intitulé) AS "Numéro et intitulé de l'opération", OPERATIONS.APA AS "AP actuelle", OPERATIONS.MICL AS "Situation MICL"
FROM OPERATIONS
INNER JOIN CHAPITRES
INNER JOIN SOUS_SECTEURS
INNER JOIN SECTEURS
ON SUBSTRING(OPERATIONS.Numéro, 7, 3) = CHAPITRES.Numéro AND CHAPITRES.SS = SOUS_SECTEURS.SS AND LEFT(SOUS_SECTEURS.SS, 1) = SECTEURS.Numéro
WHERE OPERATIONS.Localisation LIKE "%OUM-LAADHAIM%"
ORDER BY LEFT(CHAPITRES.SS, 1), CHAPITRES.SS, 1, SUBSTRING(OPERATIONS.Numéro, 7, 3), SUBSTRING(OPERATIONS.Numéro, 9, 1), SUBSTRING(OPERATIONS.Numéro, 21, 2), SUBSTRING(OPERATIONS.Numéro, 24, 2) ASC;
