SELECT OPERATIONS.MO, CONCAT(OPERATIONS.Numéro, "\n", OPERATIONS.Intitulé) AS "Numéro et intitulé de l'opération", OPERATIONS.Date_insc AS "Date d'inscription", OPERATIONS.APA AS "AP actuelle", M1.Montant AS "Engagement cumulé", M2.Montant AS "Paiment cumulé", OPERATIONS.MICL AS "Situation MICL"
FROM OPERATIONS
INNER JOIN CHAPITRES
INNER JOIN SOUS_SECTEURS
INNER JOIN SECTEURS
INNER JOIN 
(
    SELECT MOUVEMENTS.Numéro, MAX(MOUVEMENTS.Date), MOUVEMENTS.Montant
    FROM MOUVEMENTS
    WHERE MOUVEMENTS.Type = "ENG"
    GROUP BY Numéro
) AS M1
INNER JOIN 
(
    SELECT MOUVEMENTS.Numéro, SUM(MOUVEMENTS.Montant) AS "Montant"
    FROM MOUVEMENTS
    WHERE MOUVEMENTS.Type = "PAY"
    GROUP BY Numéro
) AS M2
ON SUBSTRING(OPERATIONS.Numéro, 7, 3) = CHAPITRES.Numéro AND CHAPITRES.SS = SOUS_SECTEURS.SS AND LEFT(SOUS_SECTEURS.SS, 1) = SECTEURS.Numéro AND OPERATIONS.Numéro = M1.Numéro AND OPERATIONS.Numéro = M2.Numéro
WHERE OPERATIONS.Numéro IS NOT NULL AND OPERATIONS.MICL != "Gelée" AND OPERATIONS.MICL != "Clôturé"
ORDER BY OPERATIONS.MO, CONCAT(SUBSTRING(OPERATIONS.Numéro, 1, 1), SUBSTRING(OPERATIONS.Numéro, 3, 1)), SUBSTRING(OPERATIONS.Numéro, 7, 3), SUBSTRING(OPERATIONS.Numéro, 21, 2), SUBSTRING(OPERATIONS.Numéro, 24, 2) ASC;
