SELECT CHAPITRES.SS, SUBSTRING(OPERATIONS.Numéro, 7, 3) AS "CHAPTER", CHAPITRES.DESCRIPTION, OPERATIONS.MO
FROM OPERATIONS
INNER JOIN CHAPITRES
ON SUBSTRING(OPERATIONS.Numéro, 7, 3) = CHAPITRES.Numéro
GROUP BY CHAPITRES.SS, SUBSTRING(OPERATIONS.Numéro, 7, 3), OPERATIONS.MO
ORDER BY CHAPITRES.SS, SUBSTRING(OPERATIONS.Numéro, 7, 3); 
